name: Run tests
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run all Tests
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Install project dependencies
        run: yarn --network-timeout 100000
      - name: Install visual test dependencies
        run: yarn --cwd visual-tests --network-timeout 100000
      - name: Run unit tests
        run: yarn test
      - name: Run visual tests
        run: yarn visual-test
